apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: typefast-secret
  namespace: default
spec:
  encryptedData:
    .env: AgAM8/oazLSOfLGgEI7mIq2ztO63wkSb6PkrjpF5Cojo1cO+FMAq62xptImG7TbG3Gx0ubg+Qff3gEZ8q0nPzeMd5LMQc1Lzx6us+QUW96HbGfE56UVF9uCLJS+lKS07KcB+SHa9SP4GEheDgXe1+X4g7Cetn4NaZasGHATGoPyTj9hg3QYru2iNcS64Md64TxEUKwaO34gMrYloDUlKhTf9kUzzcG6nkz9pCuzwVzQbhZJyRXmJXyfy04iQwbTeE+0dWLTxuPdIKRUrRpc+1EF/uxJllEcvYobiP/BGL61dxSo2f+kfvPBSPto5fW5uHU5XeBYLDHgXJSZnjlIY1LHWBpjaJPuOXBL+CfMbrMIw0D/abmOnkN0ZMQbAfFpBKr/SaftpQP3TLO6mI8siM2y08CzoDWea/3j8Vx+M3qHntzCrODQxf5QI5w8sxaX2QBJpS0K6OwvmaUbmvAt1RLmcQht0I7mk4XumR5OnUAlnA1TuQ99XdqaKP+U0jy2QEhxsaxixf4brjawOcmdpnktFfguNSPILYSb7e4KpxhlCCuZXywsddy5PEf65DDG0BpAKAyJslUEHjQ7Qnlp7Xv2tiGSnk+qHEdg7dP+ypgBkGKwR8H7AWg7Jx+hpBPQZ/g7gnZrtt0ySZq1ibpYmB3KHt/rediv2UEQQwPRyF48IOtatxQsiqADVwK+UXEPgFSxVnMlza1wbxqBWjK6e/stM/m4CYB0SX7pzGiCK9G7Jk6Sq6CpMGtE2Xg/KYEXZOXJzAEkfSEmHMJEqUwHTmXvFk9UNPky8JsbLwgH8uJDNC1zRp/XZpt+vmZjCNgM2n9Cf7xg9QRd4FjmMc7SyFAcQj+DCcCskPa5l87OsM0ydyvXgPtdc5Q0SrOjDn6tvIW9VDs/QUduZwbFK0SfWoIZmrTUPdRtKsocaXOsJ2UHD30ivplF0aAT8W5hK3yWccszOmwgIwz78nc3EAF1wh9i7rOp+d/SpuCTC/MTvHD6JnBdMfAI375x1NnXW70pY4Y2pUD5DvXEMtIevPY4K4yoyAOtErMx82T1ZmDBmr82DFQKV6yFFfqZvBUAxKw6FvvtckPLhpyDhVnDMP4oGDJJY9zDB90wrCNxIqXjxBTLinmhAtiNaHU/3l08bxLp3dOZfsqgdXhAlsK7H8kWJGOmzG4MzIPrMiT3gurv/HggIWryk13toz1miFvNNfMlEVmQVWCB9MY7XcRdoowrJb8453fYsdZdkq3g1RgctjxY2sqUXjyj/NNSwUBgDu/osenL8jpXRehh5gqCMIlQ9wW28oHS0XX7qWmhd9FZqgUYBo9spE6NioVu2MwRCWweYPRX6hxok7bMxUflxsHQkwJfBXJFNIzaHhJrxWpIplaKmc8afnNpkahdAJhPhjFGiH86ZHneVPhWRFDQ2t7HCZD2ME4cVs43fWm8ERPcnyAq/HuxP6b6osjPfDaueZ8hf9WJaC9nrpuOXB2dATxD9ErGl5/nopncaSgVk9xdNNV2qbOJijndccEoQb+VF+wXYhr9e5CWebw0mjnY3UspoaFFjyfZXW0UZeJg2eVDU37+Y4eP2JhJkI1LqyyvkEW2AVznb5t1v4Yt4nw+XWkcZcx6SfZXEUumafJIuyGH961zGGyJ/p1zy78km6VxCvbntwK6XqYS9TQexoderctpbnyGP7wYp3L8ExUB2KpGHXTPmOxMIBog=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: typefast-secret
      namespace: default
