apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: typefast-secret
  namespace: default
spec:
  encryptedData:
    .env: AgBP5NG7FFYCGihmaMx58lV7KUNui6S1gWfAeEL48osiw+pEimFd2HaKMct/I9ujnAjsuCwYRqrMJ9q42bnYatl2UbUyhGDBYO/YBtdSn/TC7unBzHT+Z1XMjnnovlf02nrG4FKa5XRGnKbi14Q5yySTR5JN5K5Z1Xjz5wBzXZvkigANa2Y2SuqitlxRSF2Q4lGlvEp1xGoamI1MUQKTN99hszGbsJyKUK60qkjz47h/cJEgH6xtvzilZATrhhoFqKfas5rxcdyKROjxL6PDL1Je+wX45PqftnB6166XyAa4g1yvjWWyNLPBbIpoHZXHZNR/tsrkpFJ4IpLNe9bBhRQojsG+nIHOVDCu6YMwzJ/sn3BLk7yCZ0jHZluH9N3RUj648u7smTMB5bMbQzc8PW4CdPNaR7BMxoALx9YDb9mZGt01VA5U+SKhb7rioM7N5mpd/Rasda49Z96oTxFvdbKyDqWhssW7d9vKP+I0oPVmZWzHl/fFS/xN8YqadgQV9FKY3p9JC5GpbGYWl03Rvl76XkRGCGbI4qFwFXI91+SQVkQqgtoqWzHzM6NVy3f812oBUFmJ9NYn0djCQ1X8d9bwlMnzN+Xph+uQWFldUAClZQs4h5qiyO2n3YZcSUiM+cSZsEH+gyyK9yIn2s3nV+y3u7ie1hNIYT3gjcTTdOjay7eklLCtfZwtb5n7tyaAeJoW4JMNbWax5TS+U20cOuX/twPUfckOYuG7G2BlFnqiMBjDtiJqDg8oM1DFzZ5dhsv/So4g6imCKQn0NJDZdxC7WonUmV+tJIgvWG0Y1LoDbSduU4BAM4mM+hpF/Sk2S/pYOuyBFuOsCvOZ2JlSOI2abX8W79oZMVdAZRX9XLAxtkLrgpf5IPcwcGyUcToCQXf9QGaYTk+/4txsZDHLVRAMR5JEY4ZNQid13SFKrVpd9WPYtYGLZn7mTEK78IRKscnQ+j8HTDV3WQ5TJ7q+E2h/Yx7KLJ4e6TqydMay9sT0ohvFlfk5sDrgNYorGcslHlxBBBGC1c/5pgYsZhXIofoIW8WiFyRr+n7Vwbw2BOWIpXZUhGWUTrw4TLA5ikLkRP9MMC4lJVKnrG/BBUapy6ILpRtXccOaVr9DyJNaGMin/j4VFML5gFRerD9YxbxzvyJu1MCmjJLBViKAEBYU+5QBmpocsakqfYxYvWlPpgGn6aJc9ZTIJa4yr6abaKFRYGvC9afpl4xq13tcQ4a04tRevL5VxCOlhG80MPqS3tQsyD6puREXM06eXpW29Q1kbo6454B1n+kTdGv39MSFMqcNsxfXPPtJbRDpf5wfHaJMm2GMDBV35DggSo5VUiaO8dLop69VnJaygEf8AOsHjxn+uSlWLBudavTDWRzUpISD+OEcN5049FuKsuCgDaCMF3hpDJOjOALvgTmBPTUV4K1rHUGa0nIvHXRsOFOYAd8ejQ92F00ehYg62l/IHCevalf+tHbxdzvbPdPygF9js5U2iSNbeyIZCaf8A6ZbdWcRjkuCRtC1PHNWSYXNdqtkQ31QTDlWz0FttRsI3iNStGjcdcSQQ9yxiH3ZWKhiPp/7a4zQCqTNoQ==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: typefast-secret
      namespace: default
