apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: typefast-secret
  namespace: default
spec:
  encryptedData:
    .env: AgAgNVhOiuNxTyJ2PuyyNUN2tkRo4wJbWjVLPJyiASmh1I4RDZC/XXBIEwFk/lmQX0n95Ik37GzvOQq7QpP1u1Di4Xg6yK1YIjkIyypQnDMtR8qgS4ZOlduHM7tX/c0HG0AR8p5HCiAgh/sj003YJLEbB2c7GzOEW5IZvaJ2a+HEVr+DtxLbrw4cHyCApjviHrbKi9ppGVvpEA1KwPH8x6lqnLemr93c+AucFsi6f5CnWmVbuInszRJp38dmS/5fq9uEW1dTUiopXew8Tk7H+lopte/cd1neH6o4eX8Gv/qvKv/yPzqEsjUUKag0pGaOv9Cdy1E+qEC2Sh44UUX9dQZqOAZoT5iaH3BV5DcxTWAQcqCnHm9Z92JIFJvFvXj6ei26NPGiCgOR7TVME/gt8RePpSf9GZSj4r88JW8J10+3Q9B9V/SA3/5w18QWCRpJZ8ntrW5Vm0M+5Zug90sIoJFh9kwqQ/ATKTAFaQKb7yaJkIngk1runlgF6QLgHwQGY6VdogC4OJ4LAQzbb0A+H3Zn7OTo6UO+DyLTYoT0y96Tx/8F6UGmF+8Pa36Zs6md6Ztzi2jij7BkOtLLqu2f4d0oPm/mXAwaVm74En7qgYPYcj3tjRVMMNiJudOOoQnxIXGlUVuz/spvnV4/FGmwLfRF5txZu9way23S+h7dh17uhxPIPb/g9EBClUbIY41bokXs4a2Xh8iZuOG2TxgTSrv9/DEIFCX58hZfT7OgMQ6yx1scO6mPUQRaLc7bpvhR2tDLjGgzHIVFCJ1rG5GuoMUDGTMt5SOXW+TbHKI820NYOLmjNv+wn6Ph4Ue2HLTHNnr050kMEvaclT8LumRQbvefnF7K93b3sIKSgRzOZUmuuy4WybzUU0U3mpaJfcH7nvChm4UcypZW3Rkp6tDX9T1TnWNxjRXBykki/dXVzWHdh4e2NzSjNThs47EPBUjTuNUvQZkBOVN6mcwVUfOaVHzNxuywpYywX8foAmfycifaraD+Va6EhgfigTGcniom50TSjl7UHV7GEvht3ma7aNuQnBVF73DbNwGlxzGdSryjLwSVN63QQRm4yZCnSBlS2ppzSQLaamU4SYPlgwSLtnFsSrYfnrBYnHw8F9JWIkOAnEYIiXIdMwLA3Hrkqoa5CHi3Akt1yl5eyk5hZ2jPYkhY/hufZU+7EH2ly3pRUa7clSUzV764p/JOSkkdgqPpnOFTsyQj78HHiH7CH3crqPHPRyLLGh1lup1s5xGCjJTEyDfZ6H4YMEf+KEZJbuW3O1GdTQWIvrTa8XQpXDcefwNXv/SzT9w+CWUcev6FGfVM0fXo9C8XlHErlERlEvijhyFscEFQ+4YuGfpnOORL7H/e4v8gfQ4oZTsT2wpu2k9F7UizxTx0wKXslv9Le0+wAR6ipOHc/yBRT6EpLII+VLuI5LaBbcKuM2Nf1vpatejNxHwiL+y0Bd3H84joiRdQT5kXReXVYjPmx4+Gimr6mAhjsN2a4FP33qG7g6D8J0TI3eEDtVqXAkuLmlkj1kuzTPTK9SyOlYEIS0oV6N3qM0ohc8kjPDs5l2bOPGisEqU/w5R0anqou9uwMHESm3WpOIi/7eUnez3W0wY=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: typefast-secret
      namespace: default
