apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: typefast-secret
  namespace: default
spec:
  encryptedData:
    .env: AgAxr/ybJZ1BR3FPA5fbTIerQBNWT2LU0ha60GA1tl4YnYUUIR81cbtQWYamStBgt1z7mRnUPnVmPjUF70TnCES3lc1k2U8I1bwXgYkXISwcnaMqLTf3E3LEO+0Bp5g+PvBlyt/hORvWpbJJ2vD7G1aBNYUh0rDFednujqS3y1wjybJl24CZxZAqj/S1Go3NglUSocaPS/hKifFZx64WFR67O4EizrCeg9vkvfDKLpB1Sv7c7hlfs1ST1ZxzgFPIVASTQSTamMTL5bGA1lgnUw3VcLfF5Bo90JPHzcQdT0WO/N63VCnvtQcvyC1rq6+6/g/OVDO68jfWdGRmAVH631ddOIKD9PC41txRq8ctBraHxILGo4IBuIwXupAOndgitmlnbQpOFfap57b7JTvRbYDolqB7O8LOOiE0nJaF+sGErLuOvkX3yn5Aef2CZy9pNaFxLxpPh7J9EwX70FZ24h9173trGqeaqT9qfsCbCb+hRXLHkdUzJi/e2VnHxrICcwMJ+Pae0hT1R/L7xGlHrIj8PcsUjk1/eMaCs8zuXSpPETSqdThRcJzPw53amlXZHXoeqpeXiaSeYYG9iEzMmhzu9B33mvyHKI8QJGeR18umjUG8flLm+YnwZmKa0V7V7Lf+ZT1+xyd44IkwuQzHAqtVXw2tHmGX8CdIMeP3ZTeLXk6ESvOND2t1ytsN7JXt/C4EOv3IMlZXRfhTmTkv71WpmyYRfaAbsyc+WmFe/wiPQr/g35PePFCLxMbBZ72bKykQsODddP3kEDv02cU8Eh8nSbhS0cu9XI5wRV163lxNL9z/7iKduaZpPy2wILUV+qhqH02ANeN4OiM033Mdp9gDh9JchwcWuJoONBeuZscWSRRCjLdHCG6CoWQG5PUeKiswYdsB0mfFAdDAu0lGi2pS3PW1UbUrGJLUVwXk2O8ON8udnXzi+imG8RMJ50UavyF5dQ5suNlM3B+5rzZ2DC2Lu1hFvjU8NsBV4rMuHkVAyxPkitxfmQzStoN061eUvtlos+ASJj8cViFRflNemcuzOOTUbMCAHErvKTgdgM7KqiJcVIU1oWtnnyjoitLD5xFqxoCe/bdvYbHuQgae9jwDPpc0OmVj0CjMZrQco6BHsw4HDOiW5hgl6MiMn5qcLtpzUflCQvlCVnwL+PUlV/VENilLwnMPWfSJ9NpmeabzV0OMJ+x1946q1MCZq4MtYGKOb/R+WdM2RFHrilEBWirLGZbKHXGX+HURE7wQunq5ffGQ1mNq1HtwkQBmlXkxgIZ0qNE/nwARqbJv2R3HS2QPZaAHE0Ri0Als5muDJv7b3B7SPmbR/Ku8sB3eHTI46iaqExXu7J8qwBq9m5XcIA8eZlhrzhN6FyFH6v9TWry8Vl2FuiCtl4axFLCxXwY1FZvjAovZN3l78hEQk9Tg88ziA9aHCpKhDFoxmPMI5R5NxJS+N9Fg9niFlhZL49K6KPliqRVq84DGkg/7FbOVQKO8K0vY0sw3Y9zucfiuT+dbgl4sgnueMo90eN0BlDHpp+NPSNg8iAMKh4DZojnFhgVIIY7+/ijQiOkGv5EKFg1OnFsfFYH44PuWDI3Sr1vE0qQQAl9kfZRaULl5F9CkuIVyH4EfxHrx8tk7apoa/ysXAWtql4IHd7tlj/a6ia5huRuZGw94X8lFd245gWA70hT326jD23KC1g1lx5SQYAI9zP3CSd11XpdHFq7+eXwcgmtxj+Jr535Jjp1OyE3MRDJJGbvy4Y1CMNyIo94KqU2WMGfBv3Q1x0s5uWNp
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: typefast-secret
      namespace: default
