apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: typefast-secret
  namespace: default
spec:
  encryptedData:
    .env: AgBfGsgx8zHeZFXmMZgMUr/mNikHVfvEMAJFnZChzKHKndNuKm5VB1aRkfokMupcmIBrEdNFCI3v43WUJ6V9G4crEVe+Gmi1ETOI38VuuQ8yDcr1KWYuPNcm8Mv/BE4/3XU29pvdJBuTOxqA4H96hgFXykh6m3X4O1wg1uAS9x7Kw5CX8XkbVoBa8VuZnHeYHeoe7k4C4w1TGreDzWGa+hSurmD1ZaogJ47QGBXJz0udA08kRmHHo9DHAFeMs5dNLFNYnJ9+GJc6IvoJS4Uqek+PxpFcIEGC4RLFVmDScx7csUSkHim3SgW9Dqp2aWmHiNx++xbd5lQ7ksntfDlcvxrPaPxkW3xSAJobUEf50YvAz9M2O+mllySmXdvbYKOXsi5jsB8RK6jZ7CK0q9hB8UQmMumlo9sbl7BxPninWeoGYp02+CQlS5BIhprBeM9Zb1gbrvERojrlNWv2P1D4xO2L5mz7upR3rL0JPQ7bC2oyiuaq0VET08UnGMM2R/zPL1G4g4fL8QxNEdeTlGfIcyN2X4xcARsZQGeCGDqKLJB8FJckCLZndzdQMDx5lr5d5hcI2ZsWog+mmvUhyWvZ5/vdCY77VAG/PspC7KxXtgsFmlwOuK0Dc8WJbm9IkOEg2oZhbjbXRGFRIV9Np9aICQnyVNLydwCpFqzYnOruITtnPDMECsb4M1r9nvFWlTXVxLVz8p5GJBvmP1xanmgbBe4/1rW543lz1brZVinof7VmadySZ+3Z84zE0n3vAV/AQxciMYxuJz0bNo1NyxYO4BuGBnm8UE8LSxLMYOU8Po8mUkQ544azt4346zAFj3J80ybAqSVDMLTXRUc/6IDmtWVY9aqKqT4jvt1tiGk7CaOuGNQNAPq2evS7a2E7zsE8p9sbPwLfipOirYFqOFaekq2i4/kDTKqKkG0OSx67pA/GQPRn3HSTMYYhIyRbimbMP2R1i/jX06d5fWCvjDfyWVMPqslv1GbG5jiDs3Tm7FG0qkvH0AuiaaURXwfcm7jCrRjTHhb/tuFxJ5OAtOuLAupy0FXmjDrQsEPdEr5vck4N52wOw6NUuq7bsvIY7F3viFIXpvKr3Q039vmWJ9VYaxmYtKe22AVFLNbUxyHLufeyXHiXLsiqqy0D+ZV8/xFO03genXXxYu4EZSfn20pJD8SZcql6+HukSKEoraAWe3OnrZkvVozono1eV19wsEDK1eHQLlfU5fMRjQ94AmGpSgn36ECYI+QRbkIlhIII4YbFEmbD0qc7C9iTPz01vhzueXpuTLYDQm5ZE7u214XIfugubJVtJi49JerTGr0DoM6TyrAOFIh97G7qC6wVI415B2JuHXLUsPPH1H8otdfdCf9QbeZ3RB6GOV8P0RqqzOOsfiE3m604RLNHKFUW3uZ4BQ17RljzivA+RggSKmKTVZHYJrbc85P02cWyM1tOUse9WsF3QpGcKIM869wYmt83SbQmNocvhp7j6YNbFYbTCec/QBwnlnPn/4++6uQP/GFXgz3t5oEEXmPESePX9Cy02QCdvU+WCtvOT7cUyKMmm7JuZ/F0WuGwKcsTlIZJ6FtoxRPTu1YVXl0Cr6TBxm/Ngu7yyZgsBfUyKWVQozXtH6ptByVnabL273mKb5WBPuadnJz9uvGSgYc=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: typefast-secret
      namespace: default
