apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: typefast-secret
  namespace: default
spec:
  encryptedData:
    .env: AgA+7hU6prtoleJ7p5XxZKTTh6HmEi95aiqUOz3DRWbdVLAYhVsJcKLjY9jHbruER4ZbaTXMRrIcKZc3oO/Q7CuOGN0FHLSBu9pyB1EyKWW070eaRqUwvPS9oouwz12mO8jJ4Xc9eVqxKnxowbr4/ODySd1v7r8t+CqNuVahofJdXyEskI15RcQzWuWn03kYyeATvWvA3o9hpP1xF3MTtSVW1yYa+DHMce7gBS1Dn0ifw11ZJmrwVKGQnIhmb0KJ8pWibVKzpRSVRlCkTfzHe5h4yCuPX0YxT0MOb4LWZrEDHDXZKEmzrP3MYiE8f0zq2Hpt4/D811lkd/LkCzuHJTeXSfn6Dn5feHikFlfR9jf5O3EvAZ0NgyRo5Lj/z/nTjB96V8fAn2RCR/CIEmSMYCW7oACZoweV47LgdXVMciarntsJurUj4e6eMZjLtqiMmR+7d0KAxzAS4AAUKkhW59Q5tBbM3rq4r0BkhMkV7UtcGpaJJlX4Z+v4aYK/yg4NgvOoQkBOqcuZPZ2KftSsJKSzIIyQ9DKxB2YYkY0vza5eqSLTP7Nog6zwQ3cpYXyleTIxCIgz0ejpjN65zVFPZ57J1FFy6XeB+Gjl/VEkbWTC8CpHO8qlJt7ggc+kHS+mT2P2XO6WwFe9ii0dZDE5N38YkC3ovZpCwoLSJA8/W47WX/Wb6ByCHzbPiBLmRApl2w1rV/U+kKhraxSjkZKlGFmo3dqfHvWMWxtJPY5W4pLZ1Z7YCyZlBI1AS7MtUbky2W0m6Ps9YNR2fJrN3d/rtyrwb5ni6mbrW78XW+QtITVOYgH45sLLm6soYaI5kAPo3mvdaey6cdNtoObFnDwBnRoPwLlajTBX+sKd8wMERm2oM6ZKYaxKMK/FnGL5qv7a1DexRa1AJchthH3OTpf2EVqX8HTtyXgM7xhu6C1pi7sq6o9Qpt0At7Q8dhCpFS64/tZk7EzK1o6jUrjUYvsLoIHA63N9neZo6eq2TsjY01+RWTrzU7en+VyzMFwxZeJHT84f4gmJZ8nUik2FKfPSh0B9iWbygAhUPHTZSpzzEfEW1q3blKs8GpUU35I5A7L/kBTRVSTiHaQYr6dtMqO79PGSZwrrVZRZCDzgDMEWu5SQvEy/yL8AnyLLnbBCyR/nMFj96dtrlwgEtcl1SMjejhyCCHahVBmp12jrAfUMMsXzQllNWZAGvwto51nOTCJqyxFM/YCVxQxSc6g3qaU904rXxC7Rt+NCC5R2LBOWOVtUzzsJkrIk8sbXCodK/B9hzMqFwKRnNEB2L0pGLZ8Ggrpr7pIuCaWuVDJWGhxKIfBxiZsXBQ6XWhgqXyDNV8HfEE/vxxU15AAnqGuozHowz8yufnR+ogvKocZ2cvS2GlN4SqZgYT24wIYnOL8aR5jrave/mbQHYk6jurgBnbwPst8UjwgULpVnX/9L/TVM9ky+ci5GHkRtzvXRLHX2KflQBjYOZmH2o143SLe1SIYMd37aVJjBg03O3IWL8JEyVDyX9SZCGvqJt98fkzUe+i3FreGdma0Etrdv09+qDrzZVT9PTBKZZ2Jh38Mndo2H2xdLXJFzy8SodZHwIXEl5Nmo0qhm0ivpl1Xl/sw=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: typefast-secret
      namespace: default
