---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: typefast-secret
  namespace: default
spec:
  encryptedData:
    .env: AgCKDdS03eF4J39waw9HEQJYU1yBE6olZe7JW2txCBV1uG7MfuzTFr5XqGvd+TosqPt0jP8WBqSz0R2+suFb6gI+GNeq9NxvSxFcqCOvFq5yv1g+jzap2crwGNnMPku/XG/h8wYtncqq/VRPkYOg72wzR25hEo+BlZ/rzdeJghQCBXvcGO5Sd40w+QLgz99snd2NIo4dHO0FfQoAF0jMPJG1vloz5C5Hmut3EHLvSUSwzB0u+lZJSNTKTUt2XI1IwJFbhSz7vA9USaLEvCwicWt424Tu8w+pGjpNcT/3ufDaRgBQFUd2CnjkPkWKaKi1Qk22OJ8noriijxtxxc9mxONTFpK0BPDLdCkabhyrO6xIiPvbJ1A0sPSCL10KV9v4H4S5VAO1gNBNZvEOS19x6zPmeczGo9/JiOrMpccA3GUx/IgduDDF5V3Uw0TATaGgw2fuvRbwfMxbsGewC/Fk2O9ikgnjsOiGZpSZTrHLn2XqCMLvfh59/zgp8ZxZvAH4rnYbVItrV0ZLhie2iHxTGB9Ccigv0w0pbHP13QD2DM1ImcX1IpAZf83T9BhsRXGyAk+kVfh1L1AArpkdpRQRCOuMvvuFMyI50cmgWoIkZadXMahjL5AqgN3ieab83hl8kNJbDXs6d6LS/4Cu+t+TYA2arpbutQBRJRXeMJPCtqTZfMLZJBfhR/tnxluNJOTCoVzRO46hLIbD+wac7C2lioNiPDW/RhdF/9P7d5rAwq9g5v358JMwu0YYZr5OnsXNb3kFWYKd65dEo8xvoaMlvGGemLYXzSc0PsZLW7vr0XT4iwvckzr0olUnidQOk6VK2EQrMf8n93MFV1rxSQXnilLapxBvFO1gBlKYYC/cJUILdNEBFCc+utJWaXxrnYhL3IyrTup5Kb2/n6fBhVtfEJUKATANkSuc2Q7YIcsKcfqTpJWso9sk7LuUFbtgXVOa3b2e+p6fT2Ts0/IHv3YJL6ZWRmm7HQPeURi+ViDiejVupBEaWluWp7LXNOhXFaBmk/QXq5JZGpXiA/oLSJ5uenVHb/mQvMadgvKxfciEwxc94D3uPbr0NxR3zv3UAKrgKaVqdP+FExPXG3cT5zPUWX0WEjAVojx3WiaK+brZ0x8HyB8agbnIVE5nPq63FP+s7CiRG+wMYPZXs8ifWw6EajHYQTRUki/UQ8pzozhXmrJdwH90vO7jqVLNcbkxJPwhG3vWmlGj3CEdqgHqOH9qDm/WMF2TAIkbLMQS62PSVoLedfw78xL8T3+ICKqCDVmhIOYDUFqu1P0R1CQlvypFUY/HrBSkD6Fo6L3bBGnqGeDzHlXojmBrpvaIuhlSqE92ZjabtBUEmzvhn1nCZS6OxocXbz6QIJx4gV0J5lbFwfHyWVL5RcBrKJUOh5Xn/qxaf43WcaHot8xjS6lUaM6UBVY4D1fRkC2gffC0bitIlTy6VjGyBNPSnDd2vc2qP8Zdbt+N4dgIUB0W8gnc+3j1qOBN8vpn4TMQxUgOiY/H4MjDkARTUBqGZDMuGY9ThIbWwsYPa7P1z2+b04HYOamEP7ZpxjRe6JT09pytxKkvSbQ6tWtZQtYHodt0wFb+0bSJKKbijz79Rwc/8tEtd5LBTx8Piq3ceBn/lo9ZA/EmAgCb3fKXJiuuJg/lAOsBdVs=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: typefast-secret
      namespace: default
