name: Continuous Deployment (Prod)
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push web
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/Dockerfile.web
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/typefast-web:${{ github.sha }}

      - name: Build and push ws
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/Dockerfile.ws
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/typefast-ws:${{ github.sha }}

      - name: Update Kubernetes manifests
        run: |
          sed -i "s|image: ${{ secrets.DOCKERHUB_USERNAME }}/typefast-web:.*|image: ${{ secrets.DOCKERHUB_USERNAME }}/typefast-web:${{ github.sha }}|" k8s/web.yml
          sed -i "s|image: ${{ secrets.DOCKERHUB_USERNAME }}/typefast-ws:.*|image: ${{ secrets.DOCKERHUB_USERNAME }}/typefast-ws:${{ github.sha }}|" k8s/ws.yml

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add k8s/web.yml k8s/ws.yml
          git commit -m "chore: update image tags to ${{ github.sha }}"
          git push origin main
